server:
  port: 8080

spring:
  application:
    name: websocket_demo
  messages:
    basename: messages
    encoding: UTF-8

  datasource:
    url: jdbc:mysql://localhost:3306/websocket_demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    username: itsHuaan
    password: QHuan1909!
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      phone-codes-ttl-seconds: 86400

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,first_name,last_name,picture

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 28800000
  refresh-expiration: 2592000000

cloudinary:
  name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  secret-key: ${CLOUDINARY_SECRET_KEY}

app:
  feature:
    change-username:
      enabled: true
      cooldown-days: 30

  security:
    public-paths:
      - /v1/api/auth/**
      - /error
      - /ws/**
      - /index.html
      - /
      - /cms
      - /static/**
      - /css/**
      - /js/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /v1/api/helper/**
      - /v1/api/test/**
      - /v1/api/locations/**
      - /api/scores
      - /oauth2/**
      - /login/**
  otp:
    expires-minutes: 3

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /swagger-ui
